package com.aadeshandreas.ailearning.ai_learning_companion.service;

import com.aadeshandreas.ailearning.ai_learning_companion.model.Summary;
import dev.langchain4j.data.document.Document;
import dev.langchain4j.data.document.loader.FileSystemDocumentLoader;
import dev.langchain4j.data.document.parser.apache.pdfbox.ApachePdfBoxDocumentParser;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.service.AiServices;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Service class that manages the process of summarizing uploaded PDF documents using an AI model.
 */
@Service
public class DocumentService {
    private final Summarizer summarizer;

    /**
     * Constructs the DocumentService and initializes the internal Summarizer AI Service.
     *
     * @param chatModel The ChatModel instance to be used for generating summaries.
     */
    public DocumentService(ChatModel chatModel) {
        this.summarizer = AiServices.create(Summarizer.class, chatModel);
    }

    /**
     * Summarizes the content of an uploaded PDF file.
     * <p>
     * This method temporarily saves the uploaded file, parses its text content,
     * sends it to the AI for summarization, and then cleans up the temporary file.
     *
     * @param pdfFile The PDF file uploaded by the user.
     * @return A structured {@link Summary} object generated by the AI.
     * @throws Exception if an error occurs during file processing or AI interaction.
     */
    public Summary summarizePDF(MultipartFile pdfFile) throws Exception {
        // Load the document from the uploaded file
        Path tempFile = File.createTempFile("temp-", ".pdf").toPath();
        try {
            pdfFile.transferTo(tempFile);

            Document document = FileSystemDocumentLoader.loadDocument(tempFile, new ApachePdfBoxDocumentParser());

            // Get the structured summary object from the AI and return it
            return summarizer.summarize(document.text());
        } finally {
            // Ensure the temporary file is deleted even if an error occurs
            Files.deleteIfExists(tempFile);
        }
    }
}
