package com.aadeshandreas.ailearning.ai_learning_companion.model.content;


import lombok.Getter;
import lombok.Setter;

/**
 * A data model representing a structured flashcard generated by the AI.
 * <p>
 * This class serves as a Data Transfer Object (DTO) for the API response,
 * containing the key components of a flashcard. The Lombok annotations
 * {@code @Setter} and {@code @Getter} automatically generate the corresponding
 * setter and getter methods for all fields.
 */
@Getter
@Setter
public class Flashcard {
    private int id;
    private String question;
    private String answer;
    private String hint;
}
