package com.aadeshandreas.ailearning.ai_learning_companion.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * A data model representing a structured summary generated by the AI.
 * <p>
 * This class serves as a Data Transfer Object (DTO) for the API response,
 * containing the key components of a summary. The Lombok annotations
 * {@code @Setter} and {@code @Getter} automatically generate the corresponding
 * setter and getter methods for all fields.
 */
@Setter
@Getter
public class Summary implements ApiResponse {
    private String title;
    private List<String> keyPoints;

}
