package com.aadeshandreas.ailearning.ai_learning_companion.model.coding;

import lombok.Getter;
import lombok.Setter;

import java.util.List;
import java.util.UUID;

/**
 * Represents a LeetCode-style coding question generated by the AI.
 * Contains the problem description, examples, starter code, and test cases.
 */
@Getter
@Setter
public class CodingQuestion {
    private String id;              // UUID for tracking submissions
    private int topicId;            // Reference to selected topic
    private String title;           // e.g., "Validate Binary Search Tree"
    private String description;     // Full problem description
    private String difficulty;      // EASY, MEDIUM, HARD
    private List<Example> examples; // Input/output examples
    private String methodSignature; // e.g., "public boolean isValidBST(TreeNode root)"
    private String starterCode;     // Template code with TODO
    private List<TestCase> testCases; // Test cases (visible + hidden)
    private String hints;           // Optional hints
    private Constraints constraints; // Time/space complexity expectations

    /**
     * Default constructor that generates a unique ID.
     */
    public CodingQuestion() {
        this.id = UUID.randomUUID().toString();
    }
}